# This file contains the controller configuration. 

# state controller means it will publish a topic named '/joint_states' 
# which is used by other controller. This topic i.e. /joint_states
# is basically the position, velocity and torque of each joint (in simulation for now)
joint_state_controller:
  type: "joint_state_controller/JointStateController"
  publish_rate: 125  

# this is a position (trajectory) controller controller. 
# Because all three joints are controlled at the same time 
# If you want, you can load controller for each joint separately
p1_arm_controller_bis:
  type: "position_controllers/JointTrajectoryController"
  joints:
    - panda1_joint1
    - panda1_joint2
    - panda1_joint3
    - panda1_joint4
    - panda1_joint5
    - panda1_joint6
    - panda1_joint7

p2_arm_controller_bis:
  type: "position_controllers/JointTrajectoryController"
  joints:
    - panda2_joint1
    - panda2_joint2
    - panda2_joint3
    - panda2_joint4
    - panda2_joint5
    - panda2_joint6
    - panda2_joint7
