#!/usr/bin/env python

import sys

from rqt_gui.main import Main
from hmi_qt import EzPublisherPlugin

main = Main()
sys.exit(main.main(sys.argv, standalone='hmi_qt',
                   plugin_argument_provider=EzPublisherPlugin.add_arguments))
