controller_list:
  - name: panda1_arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - panda1_joint1
      - panda1_joint2
      - panda1_joint3
      - panda1_joint4
      - panda1_joint5
      - panda1_joint6
      - panda1_joint7
  - name: panda2_arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - panda2_joint1
      - panda2_joint2
      - panda2_joint3
      - panda2_joint4
      - panda2_joint5
      - panda2_joint6
      - panda2_joint7